### PR TITLE
Update business.geojson

### PR DESCRIPTION
**Pull request by cosmopeon**
Hello, could you please add Kyrylo_Kozhemyakin@epam.com as a responsible recruiter for Python positions in Prague if possible

### CODE REVIEW

**Comment by messa** [comment]
Hey, python.cz is not a recruiting site. There is no list of Python recruiters - only list of Python users.

**Comment by lspdv** [comment]
@messa but there is list of companies offering Python jobs. So lets decide people from python.cz I think!!!

**Comment by messa** [comment]
I'm sorry if my previous comment sounded aggresive. I'm not speaking on behalf of Pyvec (the orgranization maintaining Python.cz), it's rather my personal opinion and I would like to start a discussion whether we want a list of recruiters on a website or don't.

I think it's OK to have a list of companies using Python, like we already have. I find it questionable whether the URL should link to a jobs listing page - it's not very informative, and if there is any Python position, it's just short-lived information and the link will be soon outdated.

But what I don't like is adding "Kyrylo_Kozhemyakin@epam.com as a responsible recruiter for Python". I think we should not do that, because:

- we don't have a list of recruiters, like I mentioned, but it can be created
- almost every company in the already existing list is recruiting, so this would be a rendundant information. Maybe we can give the companies on the list some way to let know that they are recruiting (some icon, start etc.?)
- if we added "Kyrylo_Kozhemyakin@epam.com" to some kind of a list, it would be almost useless without a website. If the website would be "epam.com" then that would be redundant, because it would be already in the company list
- and again, the fact that this recrioter is looking for Python programmers, is short-lived
- I really hope that you mean "responsible recruiter for Epam" and no generally for all Python positions

The HR situation in Prague is pretty extreme. I would be sad if Python.cz become just a tool for increasingly aggresive recruiter manners (speaking generally, not related to this case).

**Comment by honzajavorek** [comment]
@messa I communicated with @cosmopeon over an e-mail and I think this is just misunderstanding, not an aggressive recruiter manner. EPAM is a new company here, wants to find developers, wants to be listed. @cosmopeon follows our guidelines at python.cz (the list how to find a Python dev in the Czech Republic). That's fine.

Python.cz is a community-driven site, so any Python community member can comment under any changes to it, but until the change proposal (Pull Request) is accepted or closed, it's still just comments. I think some members may have been irritated by the fact that there's link to job openings, whereas the main purpose of the listing is, as of now, list of companies, which use Python.

I explained to @cosmopeon separately in an e-mail that python.cz contains just list of companies using Python and there's currently no dedicated job board with open opportunities. It's, of course, still beneficial for the company to be listed as Python user, but by the definition of the list we would prefer if the link could lead to homepage of the company or (better) homepage of the local branch in Prague.

The request to list e-mail contact somewhere on the site or elsewhere also cannot be fulfilled until we have a separate job board, where that would be perfectly appropriate. Also please note that @cosmopeon politely added "if possible", which I by any means do not consider as aggressive :) So my only objections to this Pull Request:

- Link should be changed to link targeting a homepage
- We have currently no place where the email could be added

Thanks! 🚀

**Comment by honzajavorek** [comment]
Also, thanks for the comments - python.cz is from the very beginning designed as a community-driven site, so while me or Pyvec may keep it operating, I'd like it to be open to any opinions, objections, ideas, from all members of the local user group.

**Comment by honzajavorek** [comment]
Fixed in https://github.com/pyvec/python.cz/pull/161

**Pull request closed without merging**
