### PR TITLE
Renew Zapoj se page

### PR DESCRIPTION
**Pull request by honzajavorek**
Production server is already prepared for these changes (`GITHUB_TOKEN` is set in Supervisor), so this can be merged right away if acceptable. Closes https://github.com/pyvec/python.cz/issues/151, https://github.com/pyvec/python.cz/issues/150, https://github.com/pyvec/python.cz/issues/147, https://github.com/pyvec/python.cz/issues/144, https://github.com/pyvec/python.cz/pull/157. Couple of screenshots:

-----------

image

-----------

image

### CODE REVIEW

**Comment by encukou** [comment]
When GitHub is down, or we're over the API limit, the entire page will error out. And since there's no caching, it seems it'll be quite easy to go over the API limit in production

We're told to vote, but is there a good way to see issues with the most votes?

**Comment by honzajavorek** [comment]
The rate limit 30 requests per minute. Okay, this needs caching, but I won't have time to add it in upcoming days.

> is there a good way to see issues with the most votes

I wanted to do it, but it's not as simple as I thought. It looks like I'd have to request every issue separately. However, the reactions are IMHO still beneficial for the issue authors / readers / commenters. There's always the non-commenting majority and it's good to at least have a slight idea what's getting attention.

**Comment by encukou** [comment]
I merged this but I'm getting an Internal Server Error at http://python.cz/zapojse/.
Let me know if you have time to fix this now, otherwise I'll revert it.

**Comment by encukou** [comment]
Reverted.

**Pull request merged**
