### PR TITLE
Add Olomouc meetup

### LINKED ISSUE #235: Přidat Olomouc
Na úvodní stránce není Pyvo v Olomouci.

### PR DESCRIPTION
**Pull request by fivaldi**
Fix #235

### CODE REVIEW

**Comment by fivaldi** [comment]
I used the official picture, since python.cz seems more formal to me than pyvo.cz, where we used the less formal PYVO variant.

Or should I changed to the same (less formal) varinat here as well?

**Comment by honzajavorek** [comment]
I vote for PYVO as a nice easter egg :)

**Comment by frenzymadness** [comment]
I am also for the less formal variant! Good job!

**Comment by fivaldi** [comment]
This is ready to be reviewed again.

**Comment by fivaldi** [comment]
preview

**Comment by frenzymadness** [comment]
Why did you decide to create the 2x2 grid? Why not all for CoAs in one row?

**Comment by fivaldi** [comment]
OK, so I can change it to "3" (on row) for medium screens and "6" (2x2) for small and extra small screens... Looks reasonable?

**Comment by frenzymadness** [comment]
IMHO it is a good idea because there is a lot of space on sides (and in the middle between columns) but please wait for another review just for sure. My design skills are weak.

**Comment by honzajavorek** [comment]
I'd keep it in one row if possible. The `.meetups` thingy could be made wider to accommodate four venues. I'm not sure about the narrowest viewport though 🤔 

image

**Comment by frenzymadness** [comment]
It would be good to finish this before Thursday.

**Comment by honzajavorek** [comment]
Let's merge it now. Better to have the info public & to have non-ideal formatting, than to hold the information from being published. Any formatting issues can be fixed in a subsequent PR.

**Comment by honzajavorek** [comment]
@fivaldi Thanks for the change! 🚀 👍

screen shot 2017-11-06 at 10 15 54

**Comment by fivaldi** [comment]
@honzajavorek Thanks for merging! Next time we'll make it perfect...

**Pull request merged**
