### PR TITLE
Add "Events" page

### PR DESCRIPTION
**Pull request by honzajavorek**
Builds on top of and closes https://github.com/pyvec/python.cz/pull/268 ❤️ @mikicz 
Also closes https://github.com/pyvec/python.cz/issues/220 (the original ticket)

-----

# INDEX PAGE

image

------

# EVENTS PAGE

image

### CODE REVIEW

**Comment by honzajavorek** [comment]
One note, I'd prefer to merge this if you think it's _good enough_ and to file additional issues afterwards so we can iteratively improve this. I don't think I can spend much more time improving this in following days / weeks.

**Comment by hroncok** [comment]
Questions:

 * pyvo events don't have clickable title. that's a pyvo.cz bug?
 * same for pyworking

**Comment by messa** [comment]
I've added URLs to pyworking workshops ical export (https://pyworking.cz/workshops.ics)

**Comment by honzajavorek** [comment]
@hroncok The bug was [here](https://github.com/pyvec/python.cz/pull/280/commits/9b68c5bfb79b450c84ea726f4ca66d500633555c#diff-6296225d4cc1c32d06f0e4ae3753f477R16) but it's not there anymore so it's probably squashed. So the only missing piece are the URLs from pyvo.cz and PyWorking, but that's not python.cz's problem 😄

**Comment by honzajavorek** [comment]
Thank you all! Merging, hopefully everything's gonna be pretty much all right 🤞

**Pull request merged**
