### PR TITLE
Little cleanup

### PR DESCRIPTION
**Pull request by honzajavorek**
See commit messages for details. Feel free to merge right away if the PR feels okay.

### CODE REVIEW

**Comment by hroncok** [comment]
By removing `__init__.py`, you are creating a [namespace package](https://www.python.org/dev/peps/pep-0420/). Omitting the file certainly works, but you probably don't want to do it for sake of simplicity, rather you would only do it if creating a namespace package was your intention (here it isn't the case).

Few quotes from PEP 420 (linked above):

> If a developer knows that her package will never be a portion of a namespace package, then there is a performance advantage to it being a regular package (with an `__init__.py`). Creation and loading of a regular package can take place immediately when it is located along the path. With namespace packages, all entries in the path must be scanned before the package is created.

> Implicit package directories go against the Zen of Python.

Note that this is a rocket science to me and @encukou might be a better reviewer here. But form my dump first look at that PEP I say we want to keep the file.

@ncoghlan might also be able to tell whether removing `__init__.py` is a good idea, as he's the author of the latter quote (according to the PEP's text).

Removing encoding declarations is fine by me, it's Legacy Python, burn it with fire.

**Comment by ncoghlan** [comment]
Keeping `__init__.py` is definitely still the safer option, as there are plenty of tools that need extra configuration to handle namespace packages properly, even though the import system itself will handle them implicitly in 3.3+.

**Comment by honzajavorek** [comment]
Good, I didn't know all this! 👍

**Comment by encukou** [comment]
I've pushed the first commit.

**Comment by honzajavorek** [comment]
@encukou 😄 You just caused me a little heart attack. I nuked the last commit and force-pushed the branch back to this PR. At the very same moment the PR got marked as successfully merged and closed. I had no slightest idea what just happened.

**Comment by hroncok** [comment]
@ncoghlan Thanks.

**Pull request closed without merging**
